# Generated by Django 2.2 on 2019-04-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='data_posted',
            new_name='date_posted',
        ),
    ]
